// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8iRYTudSP2K5uVQVbenRzqWGCs_6ZEDQ',
    appId: '1:539365959640:web:4fb21a953e3fc0e1d934ad',
    messagingSenderId: '539365959640',
    projectId: 'agrismart1328',
    authDomain: 'agrismart1328.firebaseapp.com',
    storageBucket: 'agrismart1328.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd4rLu_IsUOTdA2wUS9LeBs1cYcYMUVY',
    appId: '1:539365959640:android:aeb14165a8e42c5cd934ad',
    messagingSenderId: '539365959640',
    projectId: 'agrismart1328',
    storageBucket: 'agrismart1328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TBBl0FF8Jpa2hV8yRm5h7s5bn3Kspg8',
    appId: '1:539365959640:ios:c2011a6d104811ebd934ad',
    messagingSenderId: '539365959640',
    projectId: 'agrismart1328',
    storageBucket: 'agrismart1328.appspot.com',
    iosBundleId: 'com.example.agrismart',
  );
}
